baseURL = "https://a2n-s.github.io/graphic.github.io"
# baseURL = "/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 10

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "a2n-s' Personal Website & Blog"
    subtitle = "A simple, retro theme for Hugo"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Home"
      logoHomeLink = "/"
#      logoHomeLink = "https://a2n-s.github.io/graphic.github.io"

    [[languages.en.menu.main]]
      identifier = "front"
      name = "Front page"
      url = "/"
      weight=-1
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts"
    [[languages.en.menu.main]]
      identifier = "config"
      name = "Config"
      url = "/config"

#  [languages.fr]
#    languageName = "French"
#    title = "a2n-s' Personal Website & Blog"
#    subtitle = "A simple, retro theme for Hugo"
#    owner = ""
#    keywords = ""
#    copyright = ""
#    menuMore = "Show more"
#    readMore = "Read more"
#    readOtherPosts = "Read other posts"
#    newerPosts = "Newer posts"
#    olderPosts = "Older posts"
#    missingContentMessage = "Page not found..."
#    missingBackButtonLabel = "Back to home page"
#
#    [languages.fr.params.logo]
#      logoText = "Home"
#      logoHomeLink = "/"
##      logoHomeLink = "https://a2n-s.github.io/graphic.github.io"
#
#    [[languages.fr.menu.main]]
#      identifier = "about"
#      name = "About"
#      url = "/about"
#    [[languages.fr.menu.main]]
#      identifier = "posts"
#      name = "Posts"
#      url = "/posts"
#    [[languages.fr.menu.main]]
#      identifier = "config"
#      name = "Config"
#      url = "/config"
